# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fB03NzlUjQ4I3-eeKsWSdpM_LHvM488h
"""

import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestRegressor

X_train = pd.read_csv("healthcareinsurance_preprocessing/X_train.csv")
X_test = pd.read_csv("healthcareinsurance_preprocessing/X_test.csv")
y_train = pd.read_csv("healthcareinsurance_preprocessing/y_train.csv")
y_test = pd.read_csv("healthcareinsurance_preprocessing/y_test.csv")

mlflow.set_tracking_uri("http://127.0.0.1:5000/")
mlflow.set_experiment("Healthcare Insurance Modelling")

with mlflow.start_run(run_name="rf_baseline"):
    mlflow.sklearn.autolog()

    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)