# -*- coding: utf-8 -*-
"""modelling-tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXq4ZH-RkBXKQkCqzB_g4BzRrhFhuUHI
"""

import dagshub
import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    mean_absolute_error
)

#load dataset
X_train = pd.read_csv("healthcareinsurance_preprocessing/X_train.csv")
X_test = pd.read_csv("healthcareinsurance_preprocessing/X_test.csv")
y_train = pd.read_csv("healthcareinsurance_preprocessing/y_train.csv")
y_test = pd.read_csv("healthcareinsurance_preprocessing/y_test.csv")


#dagshub
dagshub.init(
    repo_owner="khadijakubr",
    repo_name="my-first-repo",
    mlflow=True
)

mlflow.set_experiment("Healthcare Insurance Modelling Tuning")

# Hyperparameter tuning
n_estimators_list = [100, 200, 300]
max_depth_list = [10, 20, 30]

best_r2 = -np.inf

for n_estimators in n_estimators_list:
    for max_depth in max_depth_list:

        with mlflow.start_run(run_name=f"rf_{n_estimators}_{max_depth}"):

            model = RandomForestRegressor(
                n_estimators=n_estimators,
                max_depth=max_depth,
                random_state=42,
                n_jobs=-1
            )

            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)

            mse = mean_squared_error(y_test, y_pred)
            rmse = np.sqrt(mse)
            r2 = r2_score(y_test, y_pred)
            mae = mean_absolute_error(y_test, y_pred)

            # Manual logging
            mlflow.log_param("n_estimators", n_estimators)
            mlflow.log_param("max_depth", max_depth)

            mlflow.log_metric("MSE", mse)
            mlflow.log_metric("RMSE", rmse)
            mlflow.log_metric("R2", r2)
            mlflow.log_metric("MAE", mae)

            # Artefak tambahan
            plt.figure()
            plt.scatter(y_test, y_pred)
            plt.xlabel("Actual")
            plt.ylabel("Prediction")
            plt.title("Prediction vs Actual")
            plt.savefig("prediction_plot.png")
            plt.close()

            mlflow.log_artifact("prediction_plot.png")

            with open("metrics.txt", "w") as f:
                f.write(f"R2: {r2}\nRMSE: {rmse}\nMAE: {mae}")

            mlflow.log_artifact("metrics.txt")

            if r2 > best_r2:
                best_r2 = r2
                mlflow.sklearn.log_model(model, "best_model")